var config = config ||{}

config.Wrapup=[{id:"00",description:"Select Wrapup"},
	      {id:"01",description:"Liability-A/C Balance/Cheq status/ A/c Status"},
{id:"02",description:"Liability-Debit card is not working (ATM/Online)/Status"},
{id:"03",description:"Liability-Charges Related:-AMB/Debit card Fee & others"},
{id:"04",description:"Liability-A/c Transaction & Statement Request"},
{id:"05",description:"Liability-Delieverables Cheque Book/Debit Card/Welcome kit/"},
{id:"06",description:"Liability-Transaction dispute Cash not deposited-AU Bank"},
{id:"07",description:"Liability-Transaction dispute Cash not dispensed-Other Bank"},
{id:"08",description:"Liability-POS Transaction Dispute (POS or E-COM)"},
{id:"09",description:"Liability-Net banking Related Queries"},
{id:"10",description:"Liability-Payment:-NEFT/RTGS/IMPS/CHEQUE (Both inward & outward)"},
{id:"11",description:"Liability-Online transacton:-OTP Related"},
{id:"12",description:"Liability-ATM :- PIN Generation (OTP not receive at ATM & IVR issue)/Excessive PIN Tried"},
{id:"13",description:"Liability-Insta Alets/Service SMS"},
{id:"14",description:"Liability-Fraud call intimation/Misuse in a/c"},
{id:"15",description:"Liability-Debit card hotlisting/Debit card reissuance"},
{id:"16",description:"Liability-Debit Card is not working"},
{id:"17",description:"Liability Others"},
{id:"18",description:"Assets-NOC/Return of Original documents/Permit renewal/FC letter/Statement"},
{id:"19",description:"Assets-Repayment/EMI Status/Payment/ACH"},
{id:"20",description:"Assets-Assets documents -LOD Request/Welcome letter"},
{id:"21",description:"Assets Related-Others:-Deferral Amount/Loan Disbursal Status"},
{id:"22",description:"Assets-Others"},
{id:"23",description:"Other-Leads CASA/FD/LOCKER/MSME/Wheels/GL/TWL/HL/PL/BL/Credit Card"},
{id:"24",description:"Others-Non a/c Related query"},
{id:"25",description:"Others-Au Employee Query- Self or Customer related"},
{id:"26",description:"Others-Call disconnected by customer/Blank Call/Voice Not Clear"},
{id:"27",description:"Others-Customer misbehave with agents."},
{id:"28",description:"Others-Branch Related Complaint-Misbehave/No response/Denied for any Request"},
{id:"29",description:"Other General Query-Branch address,Branch Contact #,A/C Maintainance"},
{id:"30",description:"Other-Verification Failure/Third Party Called/Insurance Department"},
{id:"31",description:"Other-Collection Care or HR Department Related"},
{id:"32",description:"Others-Fraud and Misuse"},
{id:"33",description:"Others-Go Green initiative"},
{id:"34",description:"Net banking :-Login/Register related"},
{id:"35",description:"Net banking :-User ID/Password retrieval related"},
{id:"36",description:"Net banking :-Funds Transfer thru IMPS/NEFT/RTGS related"},
{id:"37",description:"Net banking :-Payee addition/deletion to make payment thru Net banking"},
{id:"38",description:"OTP Related :-Not getting OTP while using Net banking"},
{id:"39",description:"OTP Related :-Not getting OTP while making online Transaction"},
{id:"40",description:"OTP Related :-Not getting OTP while making Debit Card PIN at ATM"},
{id:"41",description:"Debit Card is Not working :-Not able to make online transaction at Merchant Website"},
{id:"42",description:"Lead:- Mutual Fund/SIP/Life Insurance/General Insurance Related"},
{id:"43",description:"Query:- Mutual Fund/SIP/Life Insurance/General Insurance related"}];

config.Customer_Care=[{id:"00",description:"Select Wrapup"},
	      {id:"01",description:"Liability-A/C Balance/Cheq status/ A/c Status"}];


config.MenuMaster=[{id:'MN_0001',Desc:'Main Menu'},
{id:'MN_0002',Desc:'Pin Collection_BlockCard'},
{id:'MN_0003',Desc:'Pin Collection_BankingServices'},
{id:'MN_0004',Desc:'Banking Services Menu'},
{id:'MN_0006',Desc:'Language Selection Menu'},
{id:'MN_0007',Desc:'Cheque Number Collection'},
{id:'MN_0008',Desc:'Old Pin Collection'},
{id:'MN_0009',Desc:'New Pin Collection'},
{id:'MN_0010',Desc:'New Pin Confirmation'},
{id:'MN_0011',Desc:'Cheque Number Collection'},
{id:'MN_0012',Desc:'Cheque Number Confirmation'},
{id:'MN_0013',Desc:'Non Registered Menu'},
{id:'MN_0014',Desc:'Mobile Number Collection'},
{id:'MN_0015',Desc:'General Menu'},
{id:'NA',Desc:'NA'},
{id:'MN_0023',Desc:'Global Menu'},
{id:'MN_0029',Desc:'Mobile/AccountNo Collection'},
{id:'MN_0040',Desc:'Expiry Date Collection'},
{id:'MN_0034',Desc:'Account number collection'},
{id:'MN_0031',Desc:'Customer ID Collection'},
{id:'MN_0037',Desc:'Debit Card Collection'},
{id:'MN_0041',Desc:'Green Pin Collection'},
{id:'MN_0042',Desc:'Green Pin Confirmation'},
{id:'NA',Desc:'NA'}]

/*Get All Call back types*/
config.CBTypes = [{ id: 0, Description: 'None' }, 
{ id: 1, Description: 'Callback' }, 
{ id: 2, Description: 'Personal Callback' }];

config.LCMURL="http://10.57.6.161/lcmwebservice/contracts/lcmwcfservice.svc/";
config.CustomApiUrl="http://10.57.6.162/AUFAPI_NEW/Screenpop/";
//config.CustomOBApiUrl="http://10.57.6.162/AUFOBAPI/Screenpop/";
config.CustomOBApiUrl="http://10.57.6.162/AUFAPI_NewFields/Screenpop/";
